### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by shiluooulihs** [oneThousand1000/coarse-to-fine-chin-editing#1]
great job!
when will you release the training code?

**Comment by oneThousand1000** [comment]
The code was finished by myself, it will take some time for me to organize the code before release.

**Comment by oneThousand1000** [comment]
> great job!
> when will you release the training code?

The code was finished by myself, it will take some time for me to organize the code before release.

**Comment by oneThousand1000** [comment]
Please refer to https://github.com/oneThousand1000/Facial-Structure-Editing-of-Portrait-Images-via-Latent-Space-Classifications
